Repository Kolosafo/octo, pull requests merged in 2024-04, with the labels that each got.

#1 feat/gridGameDesign: Layed the ground work for grid game
  app/_components/GridBox.tsx
  app/games/grid/page.tsx
  app/globals.css
  game_utils/grid/dummyData.ts
  types.ts
Labels: feature

#2 added die game
  app/_components/Die.tsx
  app/games/tenzies/page.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: feature

#4 feat/PreSchool Curriculum game type
  app/_components/InteractiveImage.tsx
  app/_hooks/useSpeechRecognition.tsx
  app/games/interactive/page.tsx
  app/page.tsx
  game_utils/Curriculum/preschoolCurriculum.json
  game_utils/gameTypes.ts
  game_utils/interactive/dummyData.ts
  package-lock.json
  package.json
  public/img/doughnut.png
  public/img/ice-cream.png
  public/img/pizza.webp
  types.ts
Labels: feature

#3 feat: timer component
  app/_components/Timer.tsx
Labels: feature

#8 gameDesign/dragandDrop/Built drag and drop game
  app/_components/dragAndDrop/draggable.tsx
  app/_components/dragAndDrop/droppable.tsx
  app/games/dragAndDrop/page.tsx
  game_utils/dragAndDrop/dummyData.ts
  package-lock.json
  package.json
  public/img/apple.png
  public/img/box.png
  types.ts
Labels: feature, game design

#9 gameDesign/paintGame/Built the Paint game
  app/_components/paint/CanvasPreview.tsx
  app/_components/paint/Colors.tsx
  app/_components/paint/SideToolBar.tsx
  app/_hooks/paintCustomHook.ts
  app/games/paint/page.tsx
  game_utils/paint/dummyData.ts
  types.ts
Labels: feature, game design

#10 Game
  app/_components/Baloon.tsx
  app/_components/Die.tsx
  app/games/baloonpop/page.tsx
  app/games/tenzies/page.tsx
  app/globals.css
  app/layout.tsx
Labels: game design

#11 feat: analytics componenets
  app/_components/BarChart.tsx
  app/_components/LineChart.tsx
  app/_components/PieChart.tsx
  app/globals.css
  next.config.mjs
  package-lock.json
Labels: feature

#12 feat/learn: User learning
  app/BaseWrapper.tsx
  app/_components/AnswerOption.tsx
  app/_components/Lesson/InteractiveLesson.tsx
  app/_components/Lesson/LessonList.tsx
  app/_components/paint/CanvasPreview.tsx
  app/_components/paint/Colors.tsx
  app/_hooks/paintCustomHook.ts
  app/games/dragAndDrop/page.tsx
  app/games/paint/page.tsx
  app/kyc/page.tsx
  app/layout.tsx
  app/learning/[subject]/page.tsx
  app/learning/curriculum/page.tsx
  app/level-assessment/page.tsx
  game_utils/gameTypes.ts
  game_utils/paint/dummyData.ts
  helpers/helper.ts
  mockups/assessment.ts
  mockups/dummyLesson.ts
  mockups/generalCurriculum.ts
  package-lock.json
  package.json
  redux/gameState/gameStateSlice.ts
  redux/lesson/lessonSlice.ts
  redux/provider.tsx
  redux/store.ts
  redux/userPerformance/userPerformance.ts
  types.ts
Labels: enhancement, feature

#17 built auth and kyc pages
  app/BaseWrapper.tsx
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/home/page.tsx
  app/kyc/page.tsx
  app/layout.tsx
  app/loading.tsx
  app/not-found.tsx
  app/page.tsx
  components/onboard.tsx
  components/sidebar.tsx
  public/logo.svg
  public/octo.png
Labels: design

#19 ui update
  app/BaseWrapper.tsx
  app/_components/AnswerOption.tsx
  app/_components/BarChart.tsx
  app/_components/Lesson/InteractiveLesson.tsx
  app/_components/Lesson/LessonList.tsx
  app/globals.css
  app/home/page.tsx
  app/kyc/page.tsx
  app/learn/[subject]/page.tsx
  app/learn/games/baloonpop/page.tsx
  app/learn/games/grid/page.tsx
  app/learn/games/interactive/page.tsx
  app/learn/games/matching/page.tsx
  app/learn/games/page.tsx
  app/learn/games/paint/page.tsx
  app/learn/games/tenzies/page.tsx
  app/learn/help/page.tsx
  app/learn/lessons/page.tsx
  app/learn/page.tsx
  app/learn/performance/page.tsx
  app/loading.tsx
  app/not-found.tsx
  app/page.tsx
  components/filter.tsx
  components/sidebar-link.tsx
  components/sidebar.tsx
  components/speech-to-text.tsx
  components/subject.tsx
  components/warmup.tsx
  mockups/subjects.ts
Labels: design

#25 minor ui changes
  app/BaseWrapper.tsx
  app/_components/Lesson/LessonList.tsx
  app/auth/kyc/page.tsx
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/games/baloonpop/page.tsx
  app/games/dragAndDrop/page.tsx
  app/games/grid/page.tsx
  app/games/interactive/page.tsx
  app/games/paint/page.tsx
  app/games/tenzies/page.tsx
  app/learn/[...subject]/page.tsx
  app/learn/curriculum/[topic]/page.tsx
  app/learn/games/page.tsx
  app/learn/layout.tsx
  app/learn/lessons/page.tsx
  app/learn/page.tsx
  app/page.tsx
  components/loader.tsx
  components/option.tsx
  components/sidebar.tsx
  package-lock.json
  public/google.svg
Labels: design

#26 [Major Update][Features and Functionality]: AI, API, AUTH etc
  api/account.ts
  api/course.ts
  api/dataApi.ts
  app/BaseWrapper.tsx
  app/ReduxWrapper.tsx
  app/_components/Lesson/InteractiveLesson.tsx
  app/_components/Lesson/LessonList.tsx
  app/_components/Loading.tsx
  app/_components/TopicCard.tsx
  app/_components/authLoading.tsx
  app/_components/subjectSearchSelect.tsx
  app/_hooks/AI/generateLessonHook.ts
  app/_hooks/authHook.ts
  app/auth/kyc/page.tsx
  app/layout.tsx
  app/learn/[...subject]/page.tsx
  app/learn/class/page.tsx
  app/learn/curriculum/[...courseObj]/page.tsx
  app/learn/curriculum/[topic]/page.tsx
  app/learn/curriculum/new/[...courseObj]/page.tsx
  app/learn/curriculum/new/[subject]/page.tsx
  app/learn/page.tsx
  app/loading.tsx
  app/new-course/page.tsx
  app/page.tsx
  components/sidebar.tsx
  gemini/curriculum/curriculumPrompt.ts
  gemini/curriculum/generateCurriculum.ts
  gemini/lesson/learn.ts
  gemini/lesson/learnLessonPrompt.ts
  gemini/setup.ts
  helpers/helper.ts
  package-lock.json
  package.json
  redux/auth/authSlice.ts
  redux/gameState/gameStateSlice.ts
  redux/learn/learnSlice.ts
  redux/lesson/lessonSlice.ts
  redux/provider.tsx
  redux/store.ts
  redux/userPerformance/userPerformance.ts
  types.ts
Labels: bug, enhancement, feature, design

#28 fix/lessonOrder: active lesson sorting
  helpers/helper.ts
  redux/learn/learnSlice.ts
Labels: bug

#32 [Feat][Quick Learn]: Created the quick learn feature
  api/course.ts
  app/_components/TopicCard.tsx
  app/_components/coursesList.tsx
  app/_components/shortCoursesList.tsx
  app/_hooks/AI/generateQuickLessonHook.ts
  app/learn/page.tsx
  app/learn/quick-learn/page.tsx
  app/new-course/page.tsx
  components/sidebar.tsx
  gemini/lesson/learnLessonPrompt.ts
  gemini/quickLearn/quickLearnPrompt.ts
  gemini/quickLearn/sytemInstruction.ts
  helpers/helper.ts
  redux/quickLearn/quickLearnSlice.ts
  redux/store.ts
  types.ts
Labels: feature

#34 [Game][Octocrush]: OctoCrush Game Built and Integrated with AI
  app/_components/Baloon.tsx
  app/_components/octoCrushGame.tsx
  app/_hooks/AI/generateOctoCrush.ts
  app/learn/games/baloonpop/page.tsx
  app/learn/games/octoCrush/page.tsx
  gemini/octoCrush/prompt.ts
  gemini/octoCrush/systemInstruction.ts
  helpers/helper.ts
  mockups/dummyOctoCrushData.ts
  package-lock.json
  package.json
  redux/learn/learnSlice.ts
Labels: feature, game design

#35 Enhance/learn: Added more subjects
  app/learn/class/page.tsx
  gemini/curriculum/curriculumPrompt.ts
  gemini/lesson/learnLessonPrompt.ts
  mockups/subjects.ts
Labels: enhancement
